<?php
use PhpCsFixer\{Config, Finder};

$finder = ( new Finder )->in( __DIR__ )->exclude( [
  'autogenerated_content', 'captcha', 'hkit',
  'java', 'phpmailer', 'pub', 'vendor', 'ws',
] );

return ( new Config )->setRules( [
  // See https://cs.symfony.com/doc/rules/index.html
  // 'align_multiline_comment' => [
  //   'comment_type' => 'phpdocs_like'
  // ],
  // 'array_indentation' => false,
  'array_syntax' => [
    'syntax' => 'short',
  ],
  // 'assign_null_coalescing_to_coalesce_equal' => true,
  // 'attribute_empty_parentheses'              => [
  //   'use_parentheses' => false
  // ],
  // 'backtick_to_shell_exec' => false,
  // 'binary_operator_spaces' => [
  //   'default' => 'align_single_space_minimal',
  //    'operators' => [
  //      '!==' => 'align_single_space_minimal',
  //      '='   => 'align_single_space_minimal',
  //      '===' => 'align_single_space_minimal',
  //      '=>'  => 'align_single_space_minimal',
  //      '|'   => 'no_space'
  //    ]
  // ],
  'blank_line_after_opening_tag' => false,
  // 'blank_lines_before_namespace' => [
  //   'min_line_breaks' => 1,
  //   'max_line_breaks' => 1
  // ],
  // 'blank_line_after_namespace'  => false,
  // 'blank_line_before_statement' => [
  //   'statements' => [
  //     'break', 'case', 'continue', 'declare', 'default', 'do',
  //     'exit', 'for', 'foreach', 'goto', 'if', 'include',
  //     'include_once', 'phpdoc', 'require', 'require_once', 'return',
  //     'switch', 'throw', 'try', 'while', 'yield', 'yield_from'
  //   ]
  // ],
  // 'blank_line_between_import_groups' => false,
  // 'braces_position'                  => [
  //   'allow_single_line_anonymous_functions'     => true,
  //   'allow_single_line_empty_anonymous_classes' => true,
  //   'anonymous_classes_opening_brace'           => 'same_line',
  //   'anonymous_functions_opening_brace'         => 'same_line',
  //   'classes_opening_brace'                     => 'same_line',
  //   'control_structures_opening_brace'          => 'same_line',
  //   'functions_opening_brace'                   => 'same_line'
  // ],
  // 'cast_spaces' => [
  //   'space' => 'single'
  // ],
  // 'class_attributes_separation' => [
  //   'elements' => [
  //     'case'         => 'none',
  //     'const'        => 'only_if_meta',
  //     'method'       => 'one',
  //     'property'     => 'only_if_meta',
  //     'trait_import' => 'none'
  //   ]
  // ],
  // 'class_definition' => [
  //   'inline_constructor_arguments'        => true,
  //   'multi_line_extends_each_single_line' => false,
  //   'single_item_single_line'             => true,
  //   'single_line'                         => true,
  //   'space_before_parenthesis'            => false
  // ],
  // 'class_reference_name_casing'       => true,
  // 'clean_namespace'                   => true,
  // 'combine_consecutive_issets'        => true,
  // 'combine_consecutive_unsets'        => true,
  // 'compact_nullable_type_declaration' => true,
  // 'concat_space'                      => [
  //   'spacing' => 'one'
  // ],
  // 'constant_case' => [
  //   'case' => 'lower'
  // ],
  // 'control_structure_braces'                => true,
  // 'control_structure_continuation_position' => [
  //   'position' => 'same_line'
  // ],
  // 'declare_equal_normalize' => [
  //   'space' => 'single'
  // ],
  // 'declare_parentheses'                  => false,
  // 'declare_strict_types'                 => false,
  // 'dir_constant'                         => true,
  // 'doctrine_annotation_array_assignment' => [
  //   'operator' => '='
  // ],
  // 'doctrine_annotation_braces' => [
  //   'syntax' => 'with_braces'
  // ],
  // 'doctrine_annotation_indentation' => [
  //   'indent_mixed_lines' => false
  // ],
  // 'doctrine_annotation_spaces' => [
  //   'before_argument_assignments' => true,
  //   'after_argument_assignments'  => true,
  //   'around_parentheses'          => false
  // ],
  // 'echo_tag_syntax' => [
  //   'format'                         => 'short',
  //   'long_function'                  => 'echo',
  //   'shorten_simple_statements_only' => false
  // ],
  // 'elseif'          => true,
  // 'empty_loop_body' => [
  //   'style' => 'semicolon'
  // ],
  // 'empty_loop_condition' => [
  //   'style' => 'while'
  // ],
  'encoding' => true,
  // 'error_suppression' => [
  //   'mute_deprecation_error' => false,
  //   'noise_remaining_usages' => true
  // ],
  // 'explicit_indirect_variable' => false,
  // 'explicit_string_variable'   => true,
  // 'full_opening_tag' => true,
  // 'fully_qualified_strict_types' => [
  //   'import_symbols'                        => true,
  //   'leading_backslash_in_global_namespace' => false
  // ],
/* Doesn't work.
  // Always removes space between function name and opening parenthesis
  // 'function_declaration' => [
  //   'closure_fn_spacing'         => 'one',
  //   'closure_function_spacing'   => 'one',
  //   'trailing_comma_single_line' => false
  // ],
 */
  // 'function_to_constant' => [
  //   'functions' => ['get_called_class', 'get_class',
  //     'get_class_this', 'php_sapi_name', 'phpversion', 'pi'
  //   ]
  // ],
  // 'general_phpdoc_annotation_remove' => [
  //   'annotations'    => ['access', 'global'],
  //   'case_sensitive' => true
  // ],
  // 'general_phpdoc_tag_rename' => [
  //   'replacements' => ['inheritDocs' => 'inheritDoc']
  // ],
  // 'get_class_to_class_keyword' => true,
  // 'global_namespace_import'    => [
  //   'import_classes'   => true,
  //   'import_constants' => null,
  //   'import_functions' => null
  // ],
  //
  // 'group_import' => [
  //    'group_types' => ['classy', 'functions', 'constants']
  //  ],
/* Does NOT append. Overwrites/replaces all!
  //
  // 'header_comment' => [
  //   'header'       => '@package WebCalendar',
  //   'comment_type' => 'PHPDoc',
  //   'location'     => 'after_open',
  //   'separate'     => 'none'
  // ],
  //
 */
  // 'heredoc_closing_marker' => [
  //   'closing_marker'           => 'EOF',
  //   'explicit_heredoc_style'   => false,
  //   'reserved_closing_markers' => [
  //     'CSS', 'DIFF', 'HTML', 'JS', 'JSON', 'MD', 'PHP',
  //     'PYTHON', 'RST', 'TS', 'SQL', 'XML', 'YAML'
  //   ]
  // ],
/*
  // too much indent
  // 'heredoc_indentation' => [
  //   'indentation' => 'same_as_start'
  // ],
 */
  // 'heredoc_to_nowdoc' => false,
  // 'include'           => true,
  // 'increment_style'   => [
  //   'style' => 'post'
  // ],
  // 'indentation_type'            => true,
  // 'integer_literal_case'        => true,
  // 'is_null'                     => true,
  // 'lambda_not_used_import'      => true,
  // 'line_ending'                 => true,
  // 'linebreak_after_opening_tag' => true,
  // 'list_syntax'                => [
  //   'syntax' => 'short'
  // ],
  // 'logical_operators'          => true,
  // 'long_to_shorthand_operator' => true,
  // 'lowercase_cast'             => true,
  // 'lowercase_keywords'         => true,
  // 'lowercase_static_reference' => true,
  // 'magic_constant_casing'      => true,
  // 'magic_method_casing'        => true,
  // 'method_argument_space'      => [
  //   'after_heredoc'                    => true,
  //   'attribute_placement'              => 'same_line',
  //   'keep_multiple_spaces_after_comma' => false,
  //   'on_multiline'                     => 'ensure_single_line'
  // ],
  // 'method_chaining_indentation'            => true,
  // 'multiline_comment_opening_closing' => true,
  // 'multiline_string_to_heredoc'            => false,
  // 'multiline_whitespace_before_semicolons' => [
  //   'strategy' => 'no_multi_line'
  // ],
  // 'native_function_casing'         => true,
  // 'native_type_declaration_casing' => true,
  // 'new_with_parentheses'           => [
  //   'anonymous_class' => true,
  //   'named_class'     => true
  // ],
  // 'no_alias_language_construct_call' => true,
  // 'no_alternative_syntax'            => [
  //   'fix_non_monolithic_code' => true
  // ],
  // 'no_binary_string'                   => true,
  // 'no_blank_lines_after_class_opening' => true,
  // 'no_blank_lines_after_phpdoc'        => true,
  // 'no_break_comment'                   => [
  //   'comment_text' => 'intentional no break'
  // ],
  // 'no_closing_tag'       => true,
  // 'no_empty_comment'     => true,
  // 'no_empty_phpdoc'      => true,
  // 'no_empty_statement'   => true,
  // 'no_extra_blank_lines' => [
  //   'tokens' => [
  //     'attribute', 'break', 'case', 'continue', 'curly_brace_block',
  //     'default', 'extra', 'parenthesis_brace_block', 'return',
  //     'square_brace_block', 'switch', 'throw', 'use_trait', 'use'
  //   ]
  // ],
  // 'no_homoglyph_names'              => true,
  // 'no_leading_import_slash'         => true,
  // 'no_leading_namespace_whitespace' => true,
  // 'no_mixed_echo_print'             => [
  //   'use' => 'echo'
  // ],
  // 'no_multiline_whitespace_around_double_arrow' => true,
  // 'no_multiple_statements_per_line'             => true,
  // 'no_leading_namespace_whitespace'             => true,
  // 'no_null_property_initialization'             => true,
  // 'no_short_bool_cast'                          => true,
  // 'no_singleline_whitespace_before_semicolons'  => true,
  // 'no_space_around_double_colon'                => true,
  // 'no_spaces_after_function_name'               => false,
  // 'no_spaces_around_offset'                     => [
  //   'positions' => ['inside']
  // ],
  // 'no_superfluous_elseif'      => true,
  // 'no_superfluous_phpdoc_tags' => [
  //   'allow_hidden_params' => true,
  //   'allow_mixed'         => true
  // ],
  // 'no_trailing_comma_in_singleline' => [
  //   'elements' => [
  //     'arguments',
  //     'array',
  //     'array_destructuring',
  //     'group_import'
  //   ]
  // ],
  // 'no_trailing_whitespace_in_comment' => true,
  // 'no_trailing_whitespace_in_string'  => true,
  'no_trailing_whitespace'            => true,
  // 'no_unneeded_braces'                => [
  //   'namespaces' => true
  // ],
  // 'no_unneeded_control_parentheses' => [
  //   'statements' => [
  //     'break', 'clone', 'continue', 'echo_print',
  //     'return', 'switch_case', 'yield'
  //   ]
  // ],
  // 'no_unneeded_import_alias'   => true,
  // 'no_unset_cast'              => true,
  // 'no_unset_on_property'       => false,
  // 'no_unused_imports'          => true,
  // 'no_useless_concat_operator' => [
  //   'juggle_simple_strings' => true
  // ],
  // 'no_useless_else'                     => true,
  // 'no_useless_nullsafe_operator'        => true,
  // 'no_useless_return'                   => true,
  // 'no_whitespace_before_comma_in_array' => true,
  // 'no_whitespace_in_blank_line'         => true,
  // 'normalize_index_brace'               => true,
  // 'not_operator_with_space'             => true,
  // 'not_operator_with_successor_space'   => true,
  // 'nullable_type_declaration'           => [
  //   'syntax' => 'question_mark'
  // ],
  // 'nullable_type_declaration_for_default_null_value' => true,
  // 'numeric_literal_separator'                        => [
  //   'override_existing' => true,
  //   'strategy'          => 'no_separator'
  // ],
  // 'object_operator_without_whitespace' => true,
  // 'octal_notation'                     => true,
  // 'operator_linebreak'                 => [
  //   'only_booleans' => false,
  //   'position'      => 'end'
  // ],
  // 'ordered_attributes' => [
  //   'sort_algorithm' => 'alpha'
  // ],
  // 'ordered_class_elements' => [
  //   'case_sensitive' => true,
  //   'order'          => ['construct', 'destruct'],
  //   'sort_algorithm' => 'alpha'
  // ],
  // 'ordered_imports' => [
  //   'case_sensitive' => false,
  //   'imports_order'  => ['const', 'class', 'function'],
  //   'sort_algorithm' => 'alpha'
  // ],
  // 'ordered_interfaces' => [
  //   'case_sensitive' => false,
  //   'direction'      => 'ascend',
  //   'order'          => 'alpha'
  // ],
  // 'ordered_types' => [
  //   'case_sensitive'  => false,
  //   'null_adjustment' => 'always_last',
  //   'sort_algorithm'  => 'alpha'
  // ],
/*
  // adds superfluous params to page header instead of item header
  // 'phpdoc_add_missing_param_annotation' => [
  //   'only_untyped' => false
  // ],
 */
  // 'phpdoc_align' => [
  //   'align'   => 'vertical',
  //   'spacing' => [
  //     'return'   => 1,
  //     '_default' => 2
  //   ]
  // ],
  // 'phpdoc_annotation_without_dot' => true,
  // 'phpdoc_indent'                 => true,
  // 'phpdoc_inline_tag_normalizer'  => [
  //   'tags' => [
  //     'example', 'id', 'inheritdoc', 'internal',
  //     'link', 'source', 'toc', 'tutorial'
  //   ]
  // ],
  // 'phpdoc_line_span' => [
  //   'const'    => 'multi',
  //   'method'   => 'multi',
  //   'property' => 'multi'
  // ],
  // 'phpdoc_no_access'    => false,
  // 'phpdoc_no_alias_tag' => [
  //   'replacements' => [
  //     'link'           => 'see',
  //     'property-read'  => 'property',
  //     'property-write' => 'property',
  //     'type'           => 'var'
  //   ]
  // ],
  // 'phpdoc_no_empty_return'       => true,
  // 'phpdoc_no_package'            => false,
  // 'phpdoc_no_useless_inheritdoc' => true,
  // 'phpdoc_order'                 => [
  //   'order' => ['param', 'throws', 'return']
  // ],
  // 'phpdoc_order_by_value' => [
  //   'annotations' => [
  //     'author', 'covers', 'coversNothing', 'dataProvider', 'depends', 'group',
  //     'internal', 'method', 'mixin', 'property', 'requires', 'throws', 'uses'
  //   ]
  // ],
  // 'phpdoc_param_order'           => true,
  // 'phpdoc_return_self_reference' => [
  //   'replacements' => [
  //     '@self'   => 'self',
  //     '@static' => 'static',
  //     '@this'   => '$this',
  //     '$self'   => 'self',
  //     '$static' => 'static',
  //     'this'    => '$this'
  //   ]
  // ],
  // 'phpdoc_scalar' => [
  //   'types' => ['boolean', 'callback', 'double', 'integer', 'real', 'str']
  // ],
  // 'phpdoc_separation' => [
  //   'groups' => [
  //     ['author', 'copyright', 'license'],
  //     ['deprecated', 'link', 'see', 'since'],
  //     ['category', 'package', 'subpackage'],
  //     ['property'],
  //     ['param'],
  //     ['return']
  //   ],
  //   'skip_unlisted_annotations' => false,
  // ],
  // 'phpdoc_single_line_var_spacing' => true,
  // 'phpdoc_summary'                 => false,
  // 'phpdoc_tag_casing'              => [
  //   'tags' => ['inheritDoc']
  // ],
  // 'phpdoc_tag_type' => [
  //   'tags' => [
  //     'see' => 'inline',
  //     'var' => 'inline'
  //   ]
  // ],
  // 'phpdoc_to_comment' => [
  //   'ignored_tags' => [
  //     'api', 'author', 'copyright', 'deprecated', 'example',
  //     'global', 'inheritDoc', 'internal', 'license', 'method',
  //     'package', 'param', 'property', 'return', 'see', 'since',
  //     'throws', 'todo', 'uses', 'var', 'version'
  //   ]
  // ],
  // 'phpdoc_trim_consecutive_blank_line_separation' => true,
  // 'phpdoc_trim'                                   => true,
  // 'phpdoc_types_order'                            => [
  //   'case_sensitive'  => false,
  //   'null_adjustment' => 'always_last',
  //   'sort_algorithm'  => 'alpha'
  // ],
  // 'phpdoc_types' => [
  //   'groups' => ['alias', 'meta', 'simple']
  // ],
  // 'phpdoc_var_annotation_correct_order' => true,
  // 'phpdoc_var_without_name'             => true,
  // 'protected_to_private'                => true,
  // 'return_assignment'                   => true,
  // 'return_to_yield_from'                => false,
  // 'return_type_declaration'             => [
  //   'space_before' => 'one'
  // ],
  // 'self_static_accessor'               => true,
  // 'semicolon_after_instruction'        => true,
  // 'short_scalar_cast'                  => true,
  // 'simple_to_complex_string_variable'  => true,
  // 'simplified_if_return'               => true,
  // 'simplified_null_return'             => true,
  'single_blank_line_at_eof'           => true,
  // 'single_class_element_per_statement' => [
  //   'elements' => ['const', 'property']
  // ],
  // 'single_import_per_statement' => [
  //   'group_to_single_imports' => false
  // ],
  // 'single_line_after_imports'   => true,
  // 'single_line_comment_spacing' => true,
  // 'single_line_empty_body'      => true,
  // 'single_line_throw'           => true,
  // 'single_quote'                => [
  //   'strings_containing_single_quote_chars' => false
  // ],
  // 'single_space_around_construct' => [
  //   'constructs_contain_a_single_space'     => ['yield_from'],
  //   'constructs_followed_by_a_single_space' => [
  //     'abstract', 'as', 'attribute', 'break', 'case', 'catch',
  //     'class', 'clone', 'comment', 'const_import', 'const',
  //     'continue', 'do', 'echo', 'else', 'elseif', 'enum',
  //     'extends', 'final', 'finally', 'for', 'foreach', 'function_import',
  //     'function', 'global', 'goto', 'if', 'implements', 'include_once',
  //     'include', 'instanceof', 'insteadof', 'interface', 'match',
  //     'named_argument', 'namespace', 'new', 'open_tag_with_echo',
  //     'php_doc', 'php_open', 'print', 'private', 'protected', 'public',
  //     'readonly', 'require_once', 'require', 'return', 'static',
  //     'switch', 'throw', 'trait', 'try', 'type_colon', 'use_lambda',
  //     'use_trait', 'use', 'var', 'while', 'yield_from', 'yield'
  //   ],
  //   'constructs_preceded_by_a_single_space' => [
  //     'as', 'use_lambda'
  //   ]
  // ],
  // 'single_trait_insert_per_statement' => true,
  // 'space_after_semicolon' => [
  //   'remove_in_empty_for_expressions' => false
  // ],
  // 'spaces_inside_parentheses' => [
  //   'space' => 'single'
  // ],
  // 'standardize_increment'  => true,
  // 'standardize_not_equals' => true,
  // 'static_lambda'          => true,
  // 'statement_indentation'  => [
  //   'stick_comment_to_next_continuous_control_statement' => true
  // ],
  'strict_comparison' => true,
  // 'strict_param'                => true,
  // 'string_implicit_backslashes' => [
  //   'double_quoted' => 'unescape',
  //   'heredoc'       => 'unescape',
  //   'single_quoted' => 'unescape'
  // ],
  // 'string_length_to_empty'         => false,
  'string_line_ending' => true,
  // 'switch_case_semicolon_to_colon' => true,
  // 'switch_case_space'              => true,
  // 'switch_continue_to_break'       => true,
  // 'ternary_operator_spaces'        => true,
  // 'ternary_to_elvis_operator'      => true,
  // 'ternary_to_null_coalescing'     => true,
  // 'trailing_comma_in_multiline'    => [
  //   'after_heredoc' => false,
  //   'elements'      => []
  // ],
  // 'trim_array_spaces' => false,
  // 'type_declaration_spaces' => [
  //   'elements' => ['function', 'property']
  // ],
  // 'types_spaces' => [
  //   'space'                => 'none',
  //   'space_multiple_catch' => null
  // ],
  // 'unary_operator_spaces' => [
  //   'only_dec_inc' => false
  // ],
  // 'use_arrow_functions' => false,
  // 'visibility_required' => [
  //   'elements' => ['const', 'method', 'property']
  // ],
  // 'void_return'                     => false,
  // 'whitespace_after_comma_in_array' => [
  //   'ensure_single_space' => true
  // ],
  // 'yoda_style' => [
  //   'always_move_variable' => true,
  //   'equal'                => true,
  //   'identical'            => true,
  //   'less_and_greater'     => true
  // ]
/*
 * risky rules
 */
  // 'array_push'             => true,
  // 'combine_nested_dirname' => true,
  // 'comment_to_phpdoc'         => [
  //   'ignored_tags' => ['fixme', 'todo']
  // ],
  // 'date_time_create_from_format_call'      => true,
  // 'date_time_immutable'                    => false,
  // 'ereg_to_preg'                           => true,
  // 'final_class'                            => false,
  // 'final_internal_class'                   => false,
  // 'final_public_method_for_abstract_class' => false,
  // 'fopen_flag_order'                       => true,
  // 'fopen_flags'                            => [
  //   'b_mode' => false
  // ],
  // 'implode_call'               => true,
  // 'mb_str_functions'           => true,
  // 'modernize_strpos'           => true,
  // 'modernize_types_casting'    => true,
  // 'native_constant_invocation' => [
  //   'exclude'      => ['null', 'false', 'true'],
  //   'fix_built_in' => false,
  //   'strict'       => true
  // ],
  // 'native_function_invocation' => [
  //   'exclude' => [],
  //   'include' => ['@internal'],
  //   'scope'   => 'all',
  //   'strict'  => true
  // ],
  // 'no_alias_functions' => [
  //   'sets' => ['@all']
  // ],
  // 'no_php4_constructor'      => true,
  // 'no_unneeded_final_method' => [
  //   'private_methods' => true
  // ],
  // 'no_unreachable_default_argument_value' => true,
  // 'no_useless_sprintf'                    => true,
  // 'non_printable_character'               => [
  //   'use_escape_sequences_in_strings' => false
  // ],
  // 'ordered_traits' => [
  //   'case_sensitive' => false
  // ],
  // 'phpdoc_array_type'                        => false,
  // 'phpdoc_readonly_class_comment_to_keyword' => true,
  // 'phpdoc_list_type'                         => true,
  // 'pow_to_exponentiation'                    => true,
  // 'psr_autoloading'                          => false,
  // 'random_api_migration'                     => [
  //   'replacements' => [
  //     'getrandmax' => 'mt_getrandmax',
  //     // supposed to be cryptographically secure
  //     'rand'  => 'random_int',
  //     'srand' => 'mt_srand'
  //   ]
  // ],
  // 'self_accessor'              => true,
  // 'set_type_to_cast'           => true,
  // 'yield_from_array_to_yields' => false,
/*
 * risky and experimental rules
 */
  // 'phpdoc_to_param_type' => [
  //   'scalar_types' => true,
  //   'union_types'  => true
  // ],
  // 'phpdoc_to_property_type' => [
  //   'scalar_types' => true,
  //   'union_types'  => true
  // ],
  // 'phpdoc_to_return_type' => [
  //   'scalar_types' => true,
  //   'union_types'  => true
  // ],
  // 'regular_callable_call' => true,
/*
 * phpunit rules
 */
  // 'php_unit_attributes'      => true,
  // 'php_unit_fqcn_annotation' => true,
  // 'php_unit_internal_class'  => [
  //   'types' => ['normal', 'final']
  // ],
  // 'php_unit_method_casing' => [
  //   'case' => 'camel_case'
  // ],
  // 'php_unit_size_class' => [
  //   'group' => 'small'
  // ],
  // 'php_unit_test_class_requires_covers' = true,
/*
 * phpunit risky rules
 */
  // 'php_unit_construct' => [
  //   'assertions' => [
  //     'assertEquals', 'assertSame', 'assertNotEquals', 'assertNotSame'
  //   ]
  // ],
  // 'php_unit_data_provider_name' => [
  //   'prefix' => 'provide',
  //   'suffix' => 'Cases'
  // ]
  // 'php_unit_data_provider_return_type' => true,
  // 'php_unit_data_provider_static' => [
  //   'force' => false
  // ],
  // 'php_unit_dedicate_assert' => [
  //   'target' => 'newest'
  // ],
  // 'php_unit_dedicate_assert_internal_type' => [
  //   'target' => 'newest'
  // ],
  // 'php_unit_expectation' => [
  //   'target' => 'newest'
  // ],
  // 'php_unit_mock' => [
  //   'target' => 'newest'
  // ],
  // 'php_unit_mock_short_will_return' => true,
  // 'php_unit_namespaced' => [
  //   'target' => 'newest'
  // ],
  // 'php_unit_no_expectation_annotation' => [
  //   'target' => 'newest',
  //   'use_class_const' => true
  // ],
  // 'php_unit_set_up_tear_down_visibility' => true,
  // 'php_unit_strict'                      => [
  //   'assertions' => [
  //     'assertAttributeEquals', 'assertAttributeNotEquals',
  //     'assertEquals', 'assertNotEquals'
  //   ]
  // ],
  // 'php_unit_test_annotation' => [
  //   'style' => 'prefix'
  // ],
  // 'php_unit_test_case_static_method_calls' => [
  //   'call_type' => 'static',
  //   'methods'   => []
  // ]
] )->setIndent( '  ' )->setLineEnding( "\n" );
