# Makefile for copying files downloaded using composer into the proper location
# for use with WebCalendar.
# We onlt copy the min number of files required from the vendor directory.
# Also, compute the SHA hash to use with the integrity tag.
# We don't want WebCalendar releases to bundle every single file in the vendor directory.
# Also, composer dependency management sucks at asset management.

PHPMAILER_DIR = includes/classes/phpmailer
PHPMAILER_VENDOR_DIR = vendor/phpmailer/phpmailer/src

_DEFAULT: _phpmailer includes/load_assets.php

_phpmailer: $(PHPMAILER_DIR)/PHPMailer.php \
	$(PHPMAILER_DIR)/Exception.php \
	$(PHPMAILER_DIR)/OAuth.php \
	$(PHPMAILER_DIR)/POP3.php \
	$(PHPMAILER_DIR)/SMTP.php

$(PHPMAILER_DIR)/PHPMailer.php: $(PHPMAILER_VENDOR_DIR)/PHPMailer.php
	cp $< $@

$(PHPMAILER_DIR)/Exception.php: $(PHPMAILER_VENDOR_DIR)/Exception.php
	cp $< $@

$(PHPMAILER_DIR)/OAuth.php: $(PHPMAILER_VENDOR_DIR)/OAuth.php
	cp $< $@

$(PHPMAILER_DIR)/POP3.php: $(PHPMAILER_VENDOR_DIR)/POP3.php
	cp $< $@

$(PHPMAILER_DIR)/SMTP.php: $(PHPMAILER_VENDOR_DIR)/SMTP.php
	cp $< $@


includes/load_assets.php: Makefile \
	pub/bootstrap.min.css \
	pub/bootstrap.min.css.sha \
	pub/bootstrap.bundle.min.js \
	pub/bootstrap.bundle.min.js.sha \
	pub/jquery.min.js \
	pub/jquery.min.js.sha
	echo '<?php' > $@
	echo '// Auto-generated by make.  Do not hand-edit.' >> $@
	echo '// See Makefile in source for details..' >> $@
	echo -n '// Last updated: ' >> $@
	date >> $@
	echo "XASSETS =" | tr X '\044' >> $@
	echo -n '  _<link rel="stylesheet" href="pub/bootstrap.min.css" integrity="sha384-' | tr _ '\047' >> $@
	cat pub/bootstrap.min.css.sha | tr -d '\012' >> $@
	echo '">_ .' | tr _ '\047' >> $@
	echo -n '  _<script src="pub/jquery.min.js" integrity="sha384-' | tr _ '\047' >> $@
	cat pub/jquery.min.js.sha | tr -d '\012' >> $@
	echo '"></script>_ .' | tr _ '\047' >> $@
	echo -n '  _<script src="pub/bootstrap.bundle.min.js" integrity="sha384-' | tr _ '\047' >> $@
	cat pub/bootstrap.bundle.min.js.sha | tr -d '\012' >> $@
	echo '"></script>_ .' | tr _ '\047' >> $@
	echo '  "\\n";' >> $@
	echo '?>' >> $@

pub/bootstrap.min.css: vendor/twbs/bootstrap/dist/css/bootstrap.min.css
	cp $< $@

pub/bootstrap.min.css.sha: pub/bootstrap.min.css
	sha384sum $< | head -c 96 | xxd -r -p | base64 > $@

pub/bootstrap.bundle.min.js: vendor/twbs/bootstrap/dist/js/bootstrap.bundle.min.js
	cp $< $@

pub/bootstrap.bundle.min.js.sha: pub/bootstrap.bundle.min.js
	sha384sum $< | head -c 96 | xxd -r -p | base64 > $@

pub/jquery.min.js: vendor/components/jquery/jquery.min.js
	cp $< $@

pub/jquery.min.js.sha: pub/jquery.min.js
	sha384sum $< | head -c 96 | xxd -r -p | base64 > $@

