<?php
/* $Id$
 *
 * Description:
 * This script is intended to be used inside an IFRAME on another website
 * It can be embedded like so
 * <iframe name="minical" frameborder="0" height="190" width="250"
 *   src="http://cal/minical.php";>
 *
 * You must have public access enabled in System Settings to use this page
 * (unless you modify the $public_must_be_enabled setting below in this file).
 *
 * By default (if you do not edit this file), events for the public
 * calendar will be used.
 *
 * Input parameters:
 * You can override settings by changing the URL parameters:
 *   - cat_id: specify a category id to filter on
 *   - user: login name of calendar to display (instead of public user),
 *           if allowed by System Settings.
 *           Only NUC Calendar that are marked PUBLIC can be specified.
 *
 * Security:
 * $PUBLISH_ENABLED must be set true
 */
include_once 'includes/init.php';


// These values will be used by styles.php to customize the size of this calendar.
$DISPLAY_WEEKENDS = true;
$MINICALFONT = '11px';
$MINICALWIDTH = '160px';

if ( ! getPref ( 'PUBLISH_ENABLED' ) ) {
  header ( 'Content-Type: text/plain' );
  echo print_not_auth ();
  exit;
}
/* Configurable settings for this file. You may change the settings below to
 * change the default settings. These settings will likely move into the
 * System Settings in the web admin interface in a future release.
 */

// The HTML target window to use when clicking on the minical. You should be
// able to set this to the desired frame or window to receive the results.
$MINI_TARGET = '_blank';

// Allow the URL to override the user setting such as
// "minical.php?user=_NUC_training".
// If false, __public_ will always be used.
$allow_user_override = false;

// End configurable settings...

// Set for use elsewhere as a global.
//TODO
$login = $user;

if ( $allow_user_override ) {
  $u = $WC->getValue ( 'user', '[A-Za-z0-9_\.=@,\-]+', true );
  if ( ! empty ( $u ) )
    //TODO
    $login = $user = $u;
    // We also set $login since some functions assume that it is set.
}

if ( ! $loginData = $WC->User->loadVariables ( $WC->loginId() ) )
  die_miserable_death ( translate ( 'No such nonuser calendar' ) . ': '
     . $WC->loginId() );

if ( ( empty ( $loginData['is_public'] ) ||
    $minical_is_public != 'Y' ) )
  die_miserable_death ( translate ( 'This Calendar is not Public' ) );

$next = mktime ( 0, 0, 0, $thismonth + 1, 1, $thisyear );
$nextmonth = date ( 'm', $next );
$nextyear = date ( 'Y', $next );

$prev = mktime ( 0, 0, 0, $thismonth - 1, 1, $thisyear );
$prevmonth = date ( 'm', $prev );
$prevyear = date ( 'Y', $prev );

$startdate = mktime ( 0, 0, 0, $thismonth, 1, $thisyear );
$enddate = mktime ( 23, 59, 59, $thismonth + 1, 0, $thisyear );

// Don't display custom header.
build_header ( '', '', '', 31 );

/* Pre-Load the repeated events for quicker access. */
$repeated_events = read_repeated_events ( $user, $startdate, 
  $enddate, $WC->catId() );

/* Pre-load the non-repeating events for quicker access. */
$events = read_events ( $user, $startdate, 
  $enddate, $WC->catId() );

echo display_small_month ( $thismonth, $thisyear, true, false );

?>
  </body>
</html>
