<?php
/**
 * Autoloader for the bundled MCP SDK and its dependencies.
 *
 * GENERATED by tools/build-mcp-sdk.php from composer.lock. Do not edit;
 * rerun `make mcp-sdk` after changing the mcp/sdk requirement.
 */

spl_autoload_register(static function (string $class): void {
  static $map = [
    'phpDocumentor\\Reflection\\' => [__DIR__ . '/phpdocumentor/reflection-common/src', __DIR__ . '/phpdocumentor/reflection-docblock/src', __DIR__ . '/phpdocumentor/type-resolver/src'],
    'Doctrine\\Deprecations\\' => [__DIR__ . '/doctrine/deprecations/src'],
    'Symfony\\Component\\Uid\\' => [__DIR__ . '/symfony/uid'],
    'Symfony\\Polyfill\\Uuid\\' => [__DIR__ . '/symfony/polyfill-uuid'],
    'PHPStan\\PhpDocParser\\' => [__DIR__ . '/phpstan/phpdoc-parser/src'],
    'Psr\\EventDispatcher\\' => [__DIR__ . '/psr/event-dispatcher/src'],
    'Psr\\Http\\Message\\' => [__DIR__ . '/psr/http-factory/src', __DIR__ . '/psr/http-message/src'],
    'Webmozart\\Assert\\' => [__DIR__ . '/webmozart/assert/src'],
    'Opis\\JsonSchema\\' => [__DIR__ . '/opis/json-schema/src'],
    'Psr\\Http\\Client\\' => [__DIR__ . '/psr/http-client/src'],
    'Psr\\Http\\Server\\' => [__DIR__ . '/psr/http-server-handler/src', __DIR__ . '/psr/http-server-middleware/src'],
    'Http\\Discovery\\' => [__DIR__ . '/php-http/discovery/src'],
    'Psr\\Container\\' => [__DIR__ . '/psr/container/src'],
    'Opis\\String\\' => [__DIR__ . '/opis/string/src'],
    'Psr\\Clock\\' => [__DIR__ . '/psr/clock/src'],
    'Opis\\Uri\\' => [__DIR__ . '/opis/uri/src'],
    'Psr\\Log\\' => [__DIR__ . '/psr/log/src'],
    'Mcp\\' => [__DIR__ . '/mcp/sdk/src'],
  ];
  foreach ($map as $prefix => $dirs) {
    if (strncmp($class, $prefix, strlen($prefix)) !== 0) {
      continue;
    }
    $relative = str_replace('\\', '/', substr($class, strlen($prefix))) . '.php';
    foreach ($dirs as $dir) {
      $file = $dir . '/' . $relative;
      if (is_file($file)) {
        require $file;
        return;
      }
    }
  }
});

require_once __DIR__ . '/symfony/polyfill-uuid/bootstrap.php';
