# Docker container for WebCalendar with Sqlite
FROM php:8.1-apache

# Install SQLite3 PHP extension
RUN docker-php-ext-install pdo pdo_sqlite

# Copy the application source code to the container
COPY . /var/www/html/

# Set appropriate permissions for the web root
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
