<?php
/* $Id$
 *
 * The file contains a listing of all the current WebCalendar config settings
 * and their default values.
 *
 * NOTE: ADMIN master preferences begin with  '_'
 * If these options are set to 'N' in System Settings, the option will
 * be disabled in User Preferences.
 */
$webcalConfig = array (
  'ADD_LINK_IN_VIEWS' => 'N',
  '_ADMIN_OVERRIDE_UAC' => 'Y',
  '_ALLOW_ATTACH' => 'N',
  '_ALLOW_ATTACH_ANY' => 'N',
  '_ALLOW_ATTACH_PART' => 'N',
  '_ALLOW_COLOR_CUSTOMIZATION' => 'Y',
  '_ALLOW_COMMENTS' => 'N',
  '_ALLOW_COMMENTS_ANY' => 'N',
  '_ALLOW_COMMENTS_PART' => 'N',
  '_ALLOW_CONFLICT_OVERRIDE' => 'Y',
  '_ALLOW_EXTERNAL_HEADER' => 'N',
  '_ALLOW_EXTERNAL_USERS' => 'N',
  '_ALLOW_HTML_DESCRIPTION' => 'Y',
  '_ALLOW_SELF_REGISTRATION' => 'N',
  '_ALLOW_USER_HEADER' => 'N',
  '_ALLOW_USER_OVERRIDE' => 'Y',
  '_ALLOW_USER_THEMES' => 'Y',
  '_ALLOW_VIEW_OTHER' => 'Y',
  'APPLICATION_NAME' => 'Title',
  'APPROVE_ASSISTANT_EVENT' => 'Y',
  'AUTO_REFRESH' => 'N',
  'AUTO_REFRESH_TIME' => '0',
  'BGCOLOR' => '#FFFFFF',
  'BGIMAGE' => '',
  'BGREPEAT' => 'repeat fixed center',
  'BOLD_DAYS_IN_YEAR' => 'Y',
  'CAPTIONS' => '#B04040',
  '_ENABLE_CATEGORIES' => 'Y',
  'CELLBG' => '#C0C0C0',
  'CHECK_CONFLICTS' => 'Y',
  '_CLEARTEXT_PASSWORDS' => 'N',
  'CONFLICT_REPEAT_MONTHS' => '6',
  'CUSTOM_HEADER' => 'N',
  'CUSTOM_SCRIPT' => 'N',
  'CUSTOM_TRAILER' => 'N',
  'DATE_FORMAT' => 'LANGUAGE_DEFINED',
  'DATE_FORMAT_MD' => 'LANGUAGE_DEFINED',
  'DATE_FORMAT_MY' => 'LANGUAGE_DEFINED',
  'DATE_FORMAT_TASK' => 'LANGUAGE_DEFINED',
  '_DEFAULT_MINICAL_USER' => '0',
  '_DEFAULT_PUBLISH_USER' => '0',
  '_DEFAULT_RSS_USER' => '0',
  '_DEFAULT_UPCOMING_USER' => '0',
  '_DEMO_MODE' => 'N',
  'DISPLAY_ALL_DAYS_IN_MONTH' => 'N',
  'DISPLAY_CREATED_BYPROXY' => 'Y',
  'DISPLAY_DESC_PRINT_DAY' => 'Y',
  'DISPLAY_END_TIMES' => 'N',
  'DISPLAY_EMPTY_CELLS' => 'Y',
  'DISPLAY_LOCATION' => 'N',
  'DISPLAY_LONG_DAYS' => 'N',
  'DISPLAY_MINUTES' => 'N',
  'DISPLAY_MOON_PHASES' => 'N',
  'DISPLAY_SM_MONTH' => 'Y',
  'DISPLAY_TASKS' => 'N',
  'DISPLAY_TASKS_IN_GRID' => 'N',
  'DISPLAY_UNAPPROVED' => 'Y',
  'DISPLAY_WEEKENDS' => 'Y',
  'DISPLAY_WEEKNUMBER' => 'Y',
  'EMAIL_ASSISTANT_EVENTS' => 'Y',
  'EMAIL_EVENT_ADED' => 'Y',
  'EMAIL_EVENT_CRETE' => 'N',
  'EMAIL_EVENT_DELTED' => 'Y',
  'EMAIL_EVENT_REJCTED' => 'Y',
  'EMAIL_EVENT_UPDTED' => 'Y',
  '_EMAIL_FALLBACK_FROM' => 'youremailhere',
  'EMAIL_HTML' => 'N',
  '_EMAIL_MAILER' => 'mail',
  'EMAIL_REMINDER' => 'Y',
  '_ENABLE_ACCESS_FIELD' => 'Y',
  '_ENABLE_CAPTCHA' => 'N',
  '_ENABLE_CROSSDAY_EVENTS' => 'Y',
  '_ENABLE_LOCATION_FIELD' => 'Y',
  '_ENABLE_FREEBUSY' => 'N',
  'ENABLE_GRADIENTS' => 'N',
  '_ENABLE_GROUPS' => 'N',
  '_ENABLE_ICON_UPLOADS' => 'N',
  'ENABLE_MENU' => 'Y',
  '_ENABLE_NONUSERS' => 'Y',
  '_ENABLE_PARTICIPANTS_FIELD' => 'Y',
  'ENABLE_POPUPS' => 'Y',
  '_ENABLE_PRIORITY_FIELD' => 'Y',
  '_ENABLE_PUBLISH' => 'Y',
  '_ENABLE_REMINDER_FIELD' => 'Y',
  '_ENABLE_REMOTES' => 'N',
  '_ENABLE_REPORTS' => 'N',
  '_ENABLE_RSS' => 'N',
  'ENABLE_USER_PUBLISH' => 'Y',
  'ENABLE_USER_PUBLISH_RW' => 'Y',
  'ENABLE_USER_RSS' => 'N',
  '_ENABLE_URL_FIELD' => 'N',
  'ENTRY_SLOTS' => '144',
  '_EVENT_EDIT_TABS' => 'Y',
  '_EXPIRE_PASSWORDS' => '0',
  '_EXTENDED_USER' => 'N',
  '_EXTERNAL_NOTIFICATIONS' => 'N',
  '_EXTERNAL_REMINDERS' => 'N',
  'FONTS' => 'Arial, Helvetica, sans-serif',
  'GENERAL_USE_GMT' => 'Y',
  'H2COLOR' => '#000000',
  'HASEVENTSBG' => '#FFFF33',
  '_IMPORT_CATEGORIES' => 'Y',
  'LANGUAGE' => 'none',
  '_LIMIT_APPTS' => 'N',
  '_LIMIT_APPTS_NUMBER' => '6',
  '_LIMIT_DESCRIPTION_SIZE' => 'N',
  'MENU_DATE_TOP' => 'Y',
  'MYEVENTS' => '#006000',
  '_NONUSER_AT_TOP' => 'Y',
  'OTHERMONTHBG' => '#D0D0D0',
  'OVERRIDE_PUBLIC' => 'N',
  'OVERRIDE_PUBLIC_TEXT' => 'Not available',
  'PARTICIPANTS_IN_POPUP' => 'N',
  'POPUP_BG' => '#FFFFFF',
  'POPUP_FG' => '#000000',
  'PUBLIC_ACCESS' => 'N',
  'PUBLIC_ACCESS_ADD_NEEDS_APPROVAL' => 'N',
  'PUBLIC_ACCESS_CAN_ADD' => 'N',
  'PUBLIC_ACCESS_DEFAULT_SELECTED' => 'N',
  'PUBLIC_ACCESS_DEFAULT_VISIBLE' => 'N',
  'PUBLIC_ACCESS_OTHERS' => 'Y',
  'PUBLIC_ACCESS_VIEW_PART' => 'N',
  'PULLDOWN_WEEKNUMBER' => 'N',
  'REMEMBER_LAST_LOGIN' => 'N',
  'REMINDER_DEFAULT' => 'N',
  'REMINDER_OFFSET' => '240',
  'REMINDER_WITH_DATE' => 'N',
  'REQUIRE_APPROVALS' => 'Y',
  '_RESTRICT_NUC_EDITS_BY_IP' => 'Y',
  '_SELF_REGISTRATION_BLACKLIST' => 'N',
  '_SELF_REGISTRATION_FULL' => 'Y',
  '_SEND_EMAIL' => 'N',
  '_SERVER_TIMEZONE' => 'America/New_York',
  'SITE_EXTRAS_IN_POPUP' => 'N',
  '_SMTP_AUTH' => 'N',
  '_SMTP_HOST' => 'localhost',
  '_SMTP_PASSWORD' => '',
  '_SMTP_PORT' => '25',
  '_SMTP_USERNAME' => '',
  'STARTVIEW' => 'month.php',
  'STAY_IN_VIEW' => 'Y',
  'SUMMARY_LENGTH' => '80',
  'TABLEBG' => '#000000',
  'TEXTCOLOR' => '#000000',
  'THBG' => '#FFFFFF',
  'THFG' => '#000000',
  'TIME_FORMAT' => '12',
  'TIME_SLOTS' => '24',
  'TIME_SPACER' => '&raquo;&nbsp;',
  'TIMED_EVT_LEN' => 'D',
  'TIMEZONE' => 'America/New_York',
  'TODAYCELLBG' => '#FFFF33',
  '_USER_SEES_ONLY_HIS_GROUPS' => 'Y',
  'USER_SORT_ORDER' => 'cal_lastname, cal_firstname',
  '_WEBCAL_PROGRAM_VERSION' => 'v2.0',
  'WEEK_START' => '0',
  'WEEKEND_START' => '6',
  'WEEKENDBG' => '#D0D0D0',
  'WEEKNUMBER' => '#FF6633',
  'WORK_DAY_END_HOUR' => '17',
  'WORK_DAY_START_HOUR' => '8',
  'YEARS_PRE' => 10,
  'YEARS_POST' => 2
  );

/* This function is defined here because admin.php calls it during startup.
 */
function db_load_config () {
  global $webcalConfig;

  while ( list ( $key, $val ) = each ( $webcalConfig ) ) {
    $res = dbi_execute ( 'SELECT cal_value FROM webcal_config
      WHERE cal_setting = ?', array ( $key ), false, false );
    $sql = 'INSERT INTO webcal_config ( cal_setting, cal_value ) VALUES (?,?)';
    if ( ! $res )
      dbi_execute ( $sql, array ( $key, $val ) );
    else { // SQLite returns $res always.
      $row = dbi_fetch_row ( $res );
      if ( ! isset ( $row[0] ) )
        dbi_execute ( $sql, array ( $key, $val ) );

      dbi_free_result ( $res );
    }
  }
}

?>
