<?php
// Auto-generated by make.  Do not hand-edit.
// See Makefile in source for details..
// Last updated: Thu Apr  7 16:36:27 UTC 2022
$ASSETS =
  '<link rel="stylesheet" href="pub/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn">' .
  '<script src="pub/jquery.min.js" integrity="sha384-vtXRMe3mGCbOeY7l30aIg8H9p3GdeSe4IFlP6G8JMa7o7lXvnz3GFKzPxzJdPfGK"></script>' .
  '<script src="pub/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"></script>' .
  "\n";
?>
