<?php
// Auto-generated by make.  Do not hand-edit.
// See Makefile in source for details..
// Last updated: Sun 23 Apr 2023 09:58:35 AM EDT
$ASSETS =
  '<link rel="stylesheet" href="pub/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N">' .
  '<script src="pub/jquery.min.js" integrity="sha384-vtXRMe3mGCbOeY7l30aIg8H9p3GdeSe4IFlP6G8JMa7o7lXvnz3GFKzPxzJdPfGK"></script>' .
  '<script src="pub/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"></script>' .
  "\n";
?>
