<?php

declare(strict_types=1);

// Command-line only. Served over HTTP this hands execution to anyone who can
// reach the URL, and .htaccess cannot be relied on: the Debian and Ubuntu
// default of AllowOverride None makes it a no-op.
if (PHP_SAPI !== 'cli') {
  http_response_code(403);
  exit(basename(__FILE__) . " must be run from the command line.\n");
}

/**
 * Generates docs/CODEMAPS/functions.md.
 *
 * includes/functions.php is ~6600 lines and carries most of the application.
 * Anyone touching it -- a person or an agent -- otherwise greps it from
 * scratch every time, which is slow and misses things. This produces an
 * index: function, line, and the first sentence of its docblock.
 *
 * Generated rather than written, so it cannot quietly drift out of date.
 *
 *   php tools/build-codemap.php            write the file
 *   php tools/build-codemap.php --check    exit 1 if it would change
 */

const CODEMAP_SOURCES = [
  'includes/functions.php',
  'includes/dbi4php.php',
  // The third large procedural include: every export and import path runs
  // through it, and it passes almost everything through globals.
  'includes/xcal.php',
];

$root = dirname(__DIR__);
$check = in_array('--check', $_SERVER['argv'] ?? [], true);

$markdown = build_codemap($root, CODEMAP_SOURCES);
$target = $root . '/docs/CODEMAPS/functions.md';

if ($check) {
  $current = is_file($target) ? file_get_contents($target) : '';
  if ($current === $markdown) {
    echo "Codemap is current.\n";
    exit(0);
  }
  fwrite(STDERR, "Codemap is out of date. Run: php tools/build-codemap.php\n");
  exit(1);
}

if (!is_dir(dirname($target)) && !mkdir(dirname($target), 0755, true)) {
  fwrite(STDERR, "Could not create " . dirname($target) . "\n");
  exit(1);
}

file_put_contents($target, $markdown);
echo "Wrote docs/CODEMAPS/functions.md\n";
exit(0);

/**
 * @param list<string> $sources
 */
function build_codemap(string $root, array $sources): string
{
  $out = "# Function codemap\n\n"
    . "Generated by `tools/build-codemap.php`. Do not edit; run the script.\n\n"
    . "An index of the large procedural includes, so a function can be found\n"
    . "without grepping the whole file. Line numbers are from the commit this\n"
    . "was generated at.\n\n"
    . "The Globals column is the part of the contract a signature does not\n"
    . "state. These files pass data through globals, so what a function\n"
    . "declares global says more about what it touches than its parameters\n"
    . "do: export_get_event_entry() takes two arguments and reads more than a\n"
    . "dozen globals. Half the functions indexed here declare at least one.\n";

  foreach ($sources as $rel) {
    $path = $root . '/' . $rel;
    if (!is_file($path)) {
      continue;
    }
    $functions = extract_functions($path);
    $out .= "\n## `" . $rel . "`\n\n"
      . count($functions) . " functions.\n\n"
      . "| Function | Line | Purpose | Globals |\n|---|---:|---|---|\n";
    foreach ($functions as $fn) {
      // Last column on purpose: it is the widest, and a long list pushing the
      // purpose off to the right would spoil the table for the common case of
      // a function that declares none.
      $globals = $fn['globals'] === []
        ? '—'
        : '`' . implode(', ', $fn['globals']) . '`';
      $out .= '| `' . $fn['name'] . '()` | ' . $fn['line'] . ' | '
        . $fn['purpose'] . ' | ' . $globals . " |\n";
    }
  }

  return $out;
}

/**
 * Top-level functions only. A nested closure is not something anyone needs to
 * look up by name.
 *
 * @return list<array{name: string, line: int, purpose: string,
 *   globals: list<string>}>
 */
/**
 * The global variables a function declares.
 *
 * In this codebase the globals are the interface. export_get_event_entry()
 * reads twelve of them and nothing in its signature says so, so knowing what
 * a function touches means reading the whole function. Listing them turns that
 * into one line of the map.
 *
 * Globals declared inside a nested closure count too: one the closure reads is
 * still one the function depends on.
 *
 * @param list<mixed> $tokens
 * @return list<string> names with their sigil, in the order declared
 */
function globals_declared(array $tokens, int $functionAt): array
{
  $names = [];
  $depth = 0;
  $inBody = false;
  $inGlobal = false;
  $count = count($tokens);

  for ($i = $functionAt; $i < $count; $i++) {
    $token = $tokens[$i];

    if (!is_array($token)) {
      if ($token === '{') {
        $depth++;
        $inBody = true;
      } elseif ($token === '}') {
        $depth--;
        if ($inBody && $depth === 0) {
          break;
        }
      } elseif ($token === ';') {
        $inGlobal = false;
      }
      continue;
    }

    // Same interpolation trap as the caller: these open a brace but close
    // with a plain '}'.
    if ($token[0] === T_CURLY_OPEN || $token[0] === T_DOLLAR_OPEN_CURLY_BRACES) {
      $depth++;
      continue;
    }

    if (!$inBody) {
      continue;
    }

    if ($token[0] === T_GLOBAL) {
      $inGlobal = true;
      continue;
    }

    if ($inGlobal && $token[0] === T_VARIABLE
      && !in_array($token[1], $names, true)) {
      $names[] = $token[1];
    }
  }

  return $names;
}

function extract_functions(string $path): array
{
  $src = file_get_contents($path);
  if ($src === false) {
    return [];
  }

  $tokens = token_get_all($src);
  $found = [];
  $depth = 0;
  $lastDoc = '';

  foreach ($tokens as $i => $token) {
    if (!is_array($token)) {
      if ($token === '{') {
        $depth++;
      } elseif ($token === '}') {
        $depth--;
      }
      continue;
    }

    // String interpolation opens a brace with an *array* token but closes it
    // with a plain '}'. Without counting these the depth drifts negative and
    // top-level functions stop looking top-level.
    if ($token[0] === T_CURLY_OPEN || $token[0] === T_DOLLAR_OPEN_CURLY_BRACES) {
      $depth++;
      continue;
    }

    if ($token[0] === T_DOC_COMMENT) {
      $lastDoc = $token[1];
      continue;
    }

    if ($token[0] !== T_FUNCTION || $depth !== 0) {
      continue;
    }

    // The name is the next T_STRING; anything else is a closure.
    $name = '';
    for ($j = $i + 1; $j < $i + 5 && isset($tokens[$j]); $j++) {
      if (is_array($tokens[$j]) && $tokens[$j][0] === T_STRING) {
        $name = $tokens[$j][1];
        break;
      }
      if (!is_array($tokens[$j]) && $tokens[$j] === '(') {
        break; // closure
      }
    }

    if ($name === '') {
      continue;
    }

    $found[] = [
      'name' => $name,
      'line' => $token[2],
      'purpose' => summarize($lastDoc),
      'globals' => globals_declared($tokens, $i),
    ];
    $lastDoc = '';
  }

  usort($found, static fn($a, $b) => strcasecmp($a['name'], $b['name']));

  return $found;
}

/**
 * First sentence of a docblock, flattened to one table cell.
 */
function summarize(string $doc): string
{
  if ($doc === '') {
    return '_(undocumented)_';
  }

  $lines = preg_split('/\R/', $doc) ?: [];
  $text = '';
  foreach ($lines as $line) {
    $line = trim(preg_replace('#^\s*/?\*+/?#', '', $line) ?? '');
    if ($line === '' || str_starts_with($line, '@')) {
      if ($text !== '') {
        break;
      }
      continue;
    }
    $text .= ($text === '' ? '' : ' ') . $line;
    if (str_contains($line, '.')) {
      break;
    }
  }

  $text = trim(explode('.', $text)[0]);
  if ($text === '') {
    return '_(undocumented)_';
  }
  // Pipes would break the table; backticks keep inline code readable.
  $text = str_replace('|', '\\|', $text);

  return mb_strimwidth($text, 0, 110, '…');
}
