<?php
/**
 * Copies the MCP SDK and its runtime dependencies out of vendor/ into
 * includes/classes/mcp-sdk/ so that the release zip and the Docker image
 * ship them, and writes the autoloader that loads them.
 *
 * Why this exists: neither the release zip (built from release-files) nor
 * docker/Dockerfile-prod (which never runs Composer and whose .dockerignore
 * drops vendor/) carried the SDK, so the MCP server reported itself
 * unavailable on every install that was not a git checkout with Composer run
 * (issue #796). The project already treats vendor code this way for
 * PHPMailer and the front-end assets: Composer is the source, `make` copies
 * the minimum needed into the tree, and the tree is what ships.
 *
 * What is copied, per package in the dependency closure of mcp/sdk as
 * recorded in composer.lock: every *.php file (which covers the PSR-4
 * sources, Composer "files" bootstraps and runtime resources such as
 * opis/string's res/ tables) except anything under a tests, docs, examples
 * or bin directory, plus the licence file. README, CHANGELOG, composer.json
 * and the like are left behind.
 *
 * Outputs, all under includes/classes/mcp-sdk/:
 *   <vendor>/<package>/...  the copied files
 *   autoload.php            PSR-4 loader for every package plus "files" entries
 *   packages.json           package => version, from composer.lock
 * and the block between the two marker comments in release-files, which lists
 * every file under the bundle directory so the release workflow copies them.
 *
 * Usage, from the repository root after `composer install`:
 *   php tools/build-mcp-sdk.php          (or: make mcp-sdk)
 *
 * tests/McpSdkBundleTest.php fails the build when the bundle no longer
 * matches composer.lock or vendor/, so a Dependabot bump of mcp/sdk is red
 * until this is rerun and the result committed.
 *
 * @package WebCalendar
 * @license https://gnu.org/licenses/old-licenses/gpl-2.0.html GNU GPL
 */

declare(strict_types=1);

// tools/ sits inside the web root. Refuse to run under a web SAPI before
// anything else happens; .htaccess cannot be relied on to block the URL.
if ( PHP_SAPI !== 'cli' ) {
  http_response_code ( 403 );
  exit ( basename ( __FILE__ ) . " must be run from the command line.\n" );
}

const MCP_SDK_ROOT_PACKAGE = 'mcp/sdk';
const MCP_SDK_BUNDLE_DIR = 'includes/classes/mcp-sdk';
const MCP_SDK_MARK_BEGIN =
  '# BEGIN mcp-sdk bundle (generated by tools/build-mcp-sdk.php; do not edit by hand)';
const MCP_SDK_MARK_END = '# END mcp-sdk bundle';

/** Directory names, at any depth inside a package, whose contents never ship. */
const MCP_SDK_SKIP_DIRS = ['tests', 'test', 'Tests', 'docs', 'doc', 'examples', 'example', 'bin'];

/**
 * Non-dev packages from composer.lock, keyed by name.
 *
 * @return array<string, array<string, mixed>>
 */
function mcp_sdk_lock_packages(string $lockPath): array
{
  $lock = json_decode((string) file_get_contents($lockPath), true);
  if (!is_array($lock) || !isset($lock['packages'])) {
    throw new RuntimeException("Cannot read packages from $lockPath");
  }
  $byName = [];
  foreach ($lock['packages'] as $package) {
    $byName[$package['name']] = $package;
  }
  return $byName;
}

/**
 * Names of the root package and everything it requires, transitively.
 * Platform requirements (php, ext-*) are not packages and are skipped.
 *
 * @param array<string, array<string, mixed>> $packages from mcp_sdk_lock_packages()
 * @return string[] sorted
 */
function mcp_sdk_closure(array $packages, string $root = MCP_SDK_ROOT_PACKAGE): array
{
  if (!isset($packages[$root])) {
    throw new RuntimeException("$root is not in composer.lock");
  }
  $seen = [];
  $queue = [$root];
  while ($queue !== []) {
    $name = array_shift($queue);
    if (isset($seen[$name])) {
      continue;
    }
    $seen[$name] = true;
    foreach (array_keys($packages[$name]['require'] ?? []) as $dep) {
      if (isset($packages[$dep]) && !isset($seen[$dep])) {
        $queue[] = $dep;
      }
    }
  }
  $names = array_keys($seen);
  sort($names);
  return $names;
}

/**
 * Files to copy for one package, as paths relative to the package directory.
 *
 * @return string[] sorted
 */
function mcp_sdk_package_files(string $packageDir): array
{
  if (!is_dir($packageDir)) {
    throw new RuntimeException("Package directory missing: $packageDir");
  }
  $files = [];
  $iterator = new RecursiveIteratorIterator(
    new RecursiveCallbackFilterIterator(
      new RecursiveDirectoryIterator($packageDir, FilesystemIterator::SKIP_DOTS),
      static function (SplFileInfo $current): bool {
        return !($current->isDir() && in_array($current->getFilename(), MCP_SDK_SKIP_DIRS, true));
      }
    )
  );
  foreach ($iterator as $file) {
    /** @var SplFileInfo $file */
    $relative = substr($file->getPathname(), strlen($packageDir) + 1);
    $name = $file->getFilename();
    $isLicence = (bool) preg_match('/^(LICENSE|LICENCE|COPYING)(\..*)?$/i', $name)
      && !str_contains($relative, '/');
    if ($isLicence || str_ends_with($name, '.php')) {
      $files[] = str_replace('\\', '/', $relative);
    }
  }
  sort($files);
  return $files;
}

/**
 * Every file under the bundle directory, as repo-relative paths.
 *
 * @return string[] sorted
 */
function mcp_sdk_bundle_files(string $repoRoot): array
{
  $dir = $repoRoot . '/' . MCP_SDK_BUNDLE_DIR;
  if (!is_dir($dir)) {
    return [];
  }
  $files = [];
  $iterator = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS)
  );
  foreach ($iterator as $file) {
    /** @var SplFileInfo $file */
    $files[] = MCP_SDK_BUNDLE_DIR . '/'
      . str_replace('\\', '/', substr($file->getPathname(), strlen($dir) + 1));
  }
  sort($files);
  return $files;
}

/**
 * The PSR-4 map and "files" list the bundled packages need, from their
 * composer.lock autoload sections. Prefixes are ordered longest first so
 * that Psr\Http\Server\ is tried before Psr\Http\.
 *
 * @param array<string, array<string, mixed>> $packages
 * @param string[] $names
 * @return array{psr4: array<string, string[]>, files: string[]}
 */
function mcp_sdk_autoload_map(array $packages, array $names): array
{
  $psr4 = [];
  $files = [];
  foreach ($names as $name) {
    $autoload = $packages[$name]['autoload'] ?? [];
    foreach ($autoload['psr-4'] ?? [] as $prefix => $dirs) {
      foreach ((array) $dirs as $dir) {
        $dir = rtrim((string) $dir, '/');
        $psr4[$prefix][] = $name . ($dir === '' ? '' : '/' . $dir);
      }
    }
    foreach ($autoload['files'] ?? [] as $file) {
      $files[] = $name . '/' . $file;
    }
    foreach (['psr-0', 'classmap'] as $unsupported) {
      if (!empty($autoload[$unsupported])) {
        throw new RuntimeException("$name uses $unsupported autoloading, which this tool does not generate");
      }
    }
  }
  uksort($psr4, static fn(string $a, string $b): int => strlen($b) <=> strlen($a) ?: strcmp($a, $b));
  sort($files);
  return ['psr4' => $psr4, 'files' => $files];
}

/**
 * Source of includes/classes/mcp-sdk/autoload.php.
 *
 * @param array{psr4: array<string, string[]>, files: string[]} $map
 */
function mcp_sdk_autoloader_source(array $map): string
{
  $lines = [];
  foreach ($map['psr4'] as $prefix => $dirs) {
    $quotedDirs = array_map(
      static fn(string $d): string => "__DIR__ . '/" . $d . "'",
      $dirs
    );
    $lines[] = "    " . var_export($prefix, true) . " => [" . implode(', ', $quotedDirs) . "],";
  }
  $psr4Body = implode("\n", $lines);
  $fileLines = '';
  foreach ($map['files'] as $file) {
    $fileLines .= "require_once __DIR__ . '/" . $file . "';\n";
  }
  return <<<PHP
<?php
/**
 * Autoloader for the bundled MCP SDK and its dependencies.
 *
 * GENERATED by tools/build-mcp-sdk.php from composer.lock. Do not edit;
 * rerun `make mcp-sdk` after changing the mcp/sdk requirement.
 */

spl_autoload_register(static function (string \$class): void {
  static \$map = [
$psr4Body
  ];
  foreach (\$map as \$prefix => \$dirs) {
    if (strncmp(\$class, \$prefix, strlen(\$prefix)) !== 0) {
      continue;
    }
    \$relative = str_replace('\\\\', '/', substr(\$class, strlen(\$prefix))) . '.php';
    foreach (\$dirs as \$dir) {
      \$file = \$dir . '/' . \$relative;
      if (is_file(\$file)) {
        require \$file;
        return;
      }
    }
  }
});

$fileLines
PHP;
}

/**
 * Replaces (or appends) the marker-delimited block in release-files.
 *
 * @param string[] $bundleFiles repo-relative, sorted
 */
function mcp_sdk_release_files_source(string $existing, array $bundleFiles): string
{
  $block = MCP_SDK_MARK_BEGIN . "\n" . implode("\n", $bundleFiles) . "\n" . MCP_SDK_MARK_END . "\n";
  $begin = strpos($existing, MCP_SDK_MARK_BEGIN);
  $end = strpos($existing, MCP_SDK_MARK_END);
  if ($begin !== false && $end !== false && $end > $begin) {
    $endOfLine = strpos($existing, "\n", $end);
    $after = $endOfLine === false ? '' : substr($existing, $endOfLine + 1);
    return substr($existing, 0, $begin) . $block . $after;
  }
  return rtrim($existing, "\n") . "\n" . $block;
}

/**
 * Rebuilds the bundle from vendor/ and composer.lock.
 *
 * @return array{packages: int, files: int}
 */
function mcp_sdk_build(string $repoRoot): array
{
  $packages = mcp_sdk_lock_packages($repoRoot . '/composer.lock');
  $names = mcp_sdk_closure($packages);
  $vendorDir = $repoRoot . '/vendor';
  $bundleDir = $repoRoot . '/' . MCP_SDK_BUNDLE_DIR;

  // Validate every source before touching the bundle, so a missing package
  // leaves the committed tree intact.
  $plan = [];
  foreach ($names as $name) {
    $plan[$name] = mcp_sdk_package_files($vendorDir . '/' . $name);
  }

  mcp_sdk_remove_dir($bundleDir);
  $count = 0;
  foreach ($plan as $name => $files) {
    foreach ($files as $relative) {
      $target = $bundleDir . '/' . $name . '/' . $relative;
      if (!is_dir(dirname($target)) && !mkdir(dirname($target), 0755, true)) {
        throw new RuntimeException("Cannot create " . dirname($target));
      }
      if (!copy($vendorDir . '/' . $name . '/' . $relative, $target)) {
        throw new RuntimeException("Cannot copy $name/$relative");
      }
      $count++;
    }
  }

  file_put_contents(
    $bundleDir . '/autoload.php',
    mcp_sdk_autoloader_source(mcp_sdk_autoload_map($packages, $names))
  );
  $versions = [];
  foreach ($names as $name) {
    $versions[$name] = $packages[$name]['version'];
  }
  file_put_contents(
    $bundleDir . '/packages.json',
    json_encode($versions, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n"
  );

  $releaseFiles = $repoRoot . '/release-files';
  file_put_contents(
    $releaseFiles,
    mcp_sdk_release_files_source((string) file_get_contents($releaseFiles), mcp_sdk_bundle_files($repoRoot))
  );

  return ['packages' => count($names), 'files' => $count + 2];
}

function mcp_sdk_remove_dir(string $dir): void
{
  if (!is_dir($dir)) {
    return;
  }
  $iterator = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS),
    RecursiveIteratorIterator::CHILD_FIRST
  );
  foreach ($iterator as $path) {
    /** @var SplFileInfo $path */
    $path->isDir() ? rmdir($path->getPathname()) : unlink($path->getPathname());
  }
  rmdir($dir);
}

if (PHP_SAPI === 'cli' && isset($argv[0]) && realpath($argv[0]) === __FILE__) {
  $repoRoot = dirname(__DIR__);
  if (!is_dir($repoRoot . '/vendor/' . MCP_SDK_ROOT_PACKAGE)) {
    fwrite(STDERR, "vendor/" . MCP_SDK_ROOT_PACKAGE . " is missing. Run `composer install` first.\n");
    exit(1);
  }
  $summary = mcp_sdk_build($repoRoot);
  echo "Bundled {$summary['packages']} packages, {$summary['files']} files, into "
    . MCP_SDK_BUNDLE_DIR . "/ and updated release-files.\n";
}
